# Generated by Django 2.2.4 on 2019-08-11 14:52

from django.db import migrations
import datetime

def add_0_league(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    League = apps.get_model('api', 'League')
    l0 = League(id=0,name='bc20',start_date=datetime.datetime(year=2019, month=6, day=1),end_date=datetime.datetime(year=2020,month=6,day=1),active=True,submissions_enabled=True)
    l0.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_0_league),
    ]
