# Generated by Django 2.2.4 on 2019-10-24 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190811_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='team',
        ),
        migrations.AddField(
            model_name='submission',
            name='compilation_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_id_sub', to='api.Team'),
        ),
        migrations.CreateModel(
            name='TeamSubmission',
            fields=[
                ('team_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='team_id', serialize=False, to='api.Team')),
                ('compiling', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='compiling', to='api.Submission')),
                ('last_1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_1', to='api.Submission')),
                ('last_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_2', to='api.Submission')),
                ('last_3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_3', to='api.Submission')),
                ('tour_final', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_final', to='api.Submission')),
                ('tour_qual', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_qual', to='api.Submission')),
                ('tour_seed', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_seed', to='api.Submission')),
                ('tour_sprint', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_sprint', to='api.Submission')),
            ],
        ),
    ]
