# Generated by Django 2.2.4 on 2019-11-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191109_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='game_released',
            field=models.BooleanField(default=False),
        ),
    ]
