# Generated by Django 2.2.4 on 2019-12-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191110_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='code',
        ),
        migrations.AddField(
            model_name='team',
            name='staff_team',
            field=models.BooleanField(default=False),
        ),
    ]
