# Generated by Django 2.2.8 on 2020-01-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191215_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.FloatField(default=0.001),
        ),
    ]
