# Generated by Django 2.2.8 on 2020-01-10 08:21

from django.db import migrations

def calculate_score(apps, schema_editor):
    Team = apps.get_model('api', 'Team')
    for team in Team.objects.all():
        team.score = team.mu - 3*team.sigma
        team.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_team_score'),
    ]

    operations = [
        migrations.RunPython(calculate_score),
    ]
