# Generated by Django 2.2.8 on 2020-01-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_scrimmage_tournament_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='high_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='mit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='student',
            field=models.BooleanField(default=False),
        ),
    ]
