# Generated by Django 2.2.8 on 2020-01-19 06:09

from django.db import migrations

def convert_to_elo(apps, schema_editor):
    # we want to set the elo of every team with a submission to ELO_START
    # and to ELO_NULL if no submission
    Team = apps.get_model('api', 'Team')
    TeamSubmission = apps.get_model('api', 'TeamSubmission')
    for team in Team.objects.all():
        team_sub = TeamSubmission.objects.all().get(team=team)
        if team_sub.last_1_id is not None:
            team.score = settings.ELO_START
        else:
            team.score = settings.ELO_NULL
        team.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200118_2249'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
