# Generated by Django 2.2.8 on 2020-01-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200119_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bracket_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='teamsubmission_column_name',
            field=models.TextField(default='tour_sprint_id'),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.FloatField(default=-1000000),
        ),
    ]
