# Generated by Django 2.2.8 on 2020-01-22 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200122_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsubmission',
            name='tour_hs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_hs', to='api.Submission'),
        ),
        migrations.AddField(
            model_name='teamsubmission',
            name='tour_intl_qual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_intl_qual', to='api.Submission'),
        ),
        migrations.AddField(
            model_name='teamsubmission',
            name='tour_newbie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_newbie', to='api.Submission'),
        ),
    ]
