# Generated by Django 2.2.8 on 2020-04-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200122_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='auto_accept_unranked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='international',
            field=models.BooleanField(default=True),
        ),
    ]
