# Generated by Django 2.2.8 on 2020-04-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200416_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='auto_accept_ranked',
            field=models.BooleanField(default=True),
        ),
    ]
