# Generated by Django 2.2.13 on 2020-12-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200416_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrimmage',
            name='winscore',
            field=models.IntegerField(null=True),
        ),
    ]
