# Generated by Django 2.2.13 on 2020-11-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200416_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='engine_version',
            field=models.TextField(default=''),
        ),
    ]
