# Generated by Django 2.2.13 on 2020-12-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_scrimmage_winscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrimmage',
            name='losescore',
            field=models.IntegerField(null=True),
        ),
    ]
