# Generated by Django 2.2.13 on 2021-01-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_scrimmage_losescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrimmage',
            name='status',
            field=models.TextField(choices=[('created', 'Created'), ('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('redwon', 'Red Won!'), ('bluewon', 'Blue Won!'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created'),
        ),
    ]
