# Generated by Django 2.2.13 on 2021-01-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210104_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='divisions',
            field=models.CharField(max_length=64),
        ),
    ]
