# Generated by Django 2.2.13 on 2021-01-04 08:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210104_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='divisions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('highschool', 'High School'), ('newbie', 'Newbie'), ('college', 'College'), ('pro', 'Pro')]), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='divisions',
            field=models.TextField(blank=True),
        ),
    ]
