# Generated by Django 2.2.13 on 2021-01-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210104_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrimmage',
            name='map_ids',
            field=models.TextField(blank=True),
        ),
    ]
