# Generated by Django 2.2.13 on 2021-01-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210104_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrimmage',
            name='blue_submission_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scrimmage',
            name='red_submission_id',
            field=models.IntegerField(null=True),
        ),
    ]
