# Generated by Django 2.2.13 on 2021-01-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210105_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrimmage',
            name='error_msg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='error_msg',
            field=models.TextField(blank=True),
        ),
    ]
