# Generated by Django 2.2.13 on 2021-01-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210106_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrimmage',
            name='error_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
