# Generated by Django 2.2.13 on 2021-01-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210107_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='error_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
