// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

/**
 * Actions that can be performed.
 * Purely aesthetic; have no actual effect on simulation.
 * (Although the simulation may want to track the 'parents' of
 * particular robots.)
 * Actions may have 'targets', which are the units on which
 * the actions were performed.
 */
public final class Action {
  private Action() { }
  /**
   * politicians self-destruct and affect nearby bodies
   * Target: none
   */
  public static final byte EMPOWER = 0;
  /**
   * scandals turn into politicians.
   * Target: self.
   */
  public static final byte CAMOUFLAGE = 1;
  /**
   * slanders are alowed to TODO.
   * Target: TODO.
   */
  public static final byte EMBEZZLE = 2;
  /**
   * Muckrakers can expose a scandal.
   * Target: an enemy body.
   */
  public static final byte EXPOSE = 3;
  /**
   * units can change their flag.
   * Target: self.
   */
  public static final byte SET_FLAG = 4;
  /**
   * units can get the flag of another unit
   * Target: another unit.
   */
  public static final byte GET_FLAG = 5;
  /**
   * Builds a unit (enlightent center).
   * Target: spawned unit
   */
  public static final byte SPAWN_UNIT = 6;
  /**
   * places a bet (enlightent center).
   * Target: bet placed
   */
  public static final byte PLACE_BET = 7;
  /**
   * Dies by moving into a swamp.
   * Target: drowning robot.
   */
  public static final byte DIE_DROWN = 8;
  /**
   * Dies for having zero influence.
   * Target: a politician, scandal or Muckrakers.
   */
  public static final byte DIE_ZERO_INFLUENCE = 9;
  /**
   * a robot can change team after being empowered
   * Target: self
   */
  public static final byte CHANGE_TEAM = 10;
  /**
   * an enlightenment center can become neutral if lost all its influence
   * Target: none.
   */
  public static final byte BECOME_NEUTRAL = 11;
  /**
   * Dies due to an uncaught exception
   * Target: none
   */
  public static final byte DIE_EXCEPTION = 12;

  public static final String[] names = { "EMPOWER", "CAMOUFLAGE", "EMBEZZLE", "EXPOSE", "SET_FLAG", "GET_FLAG", "SPAWN_UNIT", "PLACE_BET", "DIE_DROWN", "DIE_ZERO_INFLUENCE", "CHANGE_TEAM", "BECOME_NEUTRAL", "DIE_EXCEPTION", };

  public static String name(int e) { return names[e]; }
}

