// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

/**
 * Actions that can be performed.
 * Purely aesthetic; have no actual effect on simulation.
 * (Although the simulation may want to track the 'parents' of
 * particular robots.)
 * Actions may have 'targets', which are the units on which
 * the actions were performed.
 */
public final class Action {
  private Action() { }
  /**
   * Mines a unit of soup (miners).
   * Target: location.
   */
  public static final byte MINE_SOUP = 0;
  /**
   * Deposits a unit of soup (miners).
   * Target: refinery.
   */
  public static final byte DEPOSIT_SOUP = 1;
  /**
   * Refines a unit of soup (refinery).
   * Target: none.
   */
  public static final byte REFINE_SOUP = 2;
  /**
   * Digs a unit of dirt (landscapers).
   * Target: location.
   */
  public static final byte DIG_DIRT = 3;
  /**
   * Deposits a unit of dirt (landscapers).
   * Target: location.
   */
  public static final byte DEPOSIT_DIRT = 4;
  /**
   * Picks up a unit (drones).
   * Target: unit picked up.
   */
  public static final byte PICK_UNIT = 5;
  /**
   * Drops off a unit (drones).
   * Target: unit dropped off.
   */
  public static final byte DROP_UNIT = 6;
  /**
   * Builds a unit.
   * Target: spawned unit
   */
  public static final byte SPAWN_UNIT = 7;
  /**
   * Shoots a drone.
   * Target: drone shot.
   */
  public static final byte SHOOT = 8;
  /**
   * Dies from drowning.
   * Target: none.
   */
  public static final byte DIE_DROWN = 9;
  /**
   * Dies from being shot (drones).
   * Target: drone.
   */
  public static final byte DIE_SHOT = 10;
  /**
   * Dies due to having too much dirt on top (buildings).
   * Target: landscaper
   */
  public static final byte DIE_TOO_MUCH_DIRT = 11;
  /**
   * Dies from suicide.
   * Target: none.
   */
  public static final byte DIE_SUICIDE = 12;
  /**
   * Dies due to an uncaught exception
   * Target: none
   */
  public static final byte DIE_EXCEPTION = 13;

  public static final String[] names = { "MINE_SOUP", "DEPOSIT_SOUP", "REFINE_SOUP", "DIG_DIRT", "DEPOSIT_DIRT", "PICK_UNIT", "DROP_UNIT", "SPAWN_UNIT", "SHOOT", "DIE_DROWN", "DIE_SHOT", "DIE_TOO_MUCH_DIRT", "DIE_SUICIDE", "DIE_EXCEPTION", };

  public static String name(int e) { return names[e]; }
}

