// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
/**
 * A vector in two-dimensional space. Discrete space, of course.
 * Defaults to the 0 vector.
 */
public final class Vec extends Struct {
  public Vec __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int x() { return bb.getInt(bb_pos + 0); }
  public int y() { return bb.getInt(bb_pos + 4); }

  public static int createVec(FlatBufferBuilder builder, int x, int y) {
    builder.prep(4, 8);
    builder.putInt(y);
    builder.putInt(x);
    return builder.offset();
  }
}

